export const EVENTS = {
    INITIALIZATION: "INITIALIZATION",
    OUTGOING_CALL: "OUTGOING_CALL",
    HANG_UP_CALL: "HANG_UP_CALL",

    INVALID_CALL: "INVALID_CALL",
    _TEST: "_TEST",

    // TODO: CHANGE NAME
    OUTGOING_CALL_EXTENSION: "OUTGOING_CALL_EXTENSION",
}